---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opensearch
  namespace: infrastructure
spec:
  interval: 1h
  url: https://opensearch-project.github.io/helm-charts/
