---
docker_version: latest
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
docker_daemon_options:
  log-driver: json-file
  log-opts:
    max-size: "50m"
    max-file: "3"
