---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: magento
  namespace: apps
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`testing-magento.yosefadi.my.id`)
      services:
        - name: magento
          port: 8080
