---
all:
  children:
    minikube:
      hosts:
        minikube-throwaway:
          ansible_host: 100.93.214.65
          ansible_user: ubuntu
          ansible_become: true
          ansible_become_method: sudo
