---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-dragonfly
  namespace: apps
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: magento
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infrastructure
          podSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
      ports:
        - protocol: TCP
          port: 6379
