apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/namespace.yaml
  - infrastructure/helm-repositories/opensearch.yaml
  - infrastructure/helm-repositories/stakater.yaml
  - infrastructure/reloader/namespace.yaml
  - infrastructure/reloader/release.yaml
  - infrastructure/mariadb/statefulset.yaml
  - infrastructure/mariadb/service.yaml
  - infrastructure/opensearch/release.yaml
  - infrastructure/dragonfly/deployment.yaml
  - infrastructure/dragonfly/service.yaml
  - infrastructure/cloudflared/deployment.yaml
  - infrastructure/networkpolicies/default-deny-ingress.yaml
  - infrastructure/networkpolicies/default-deny-egress.yaml
  - infrastructure/networkpolicies/allow-egress-to-kube-dns.yaml
  - infrastructure/networkpolicies/allow-egress-to-magento.yaml
  - infrastructure/networkpolicies/allow-ingress-from-magento-mariadb.yaml
  - infrastructure/networkpolicies/allow-ingress-from-magento-opensearch.yaml
  - infrastructure/networkpolicies/allow-ingress-from-magento-dragonfly.yaml
  - apps/namespace.yaml
  - apps/magento/configmap.yaml
  - apps/magento/service.yaml
  - apps/magento/pvc.yaml
  - apps/magento/deployment.yaml
  - apps/networkpolicies/default-deny-ingress.yaml
  - apps/networkpolicies/default-deny-egress.yaml
  - apps/networkpolicies/allow-egress-to-kube-dns.yaml
  - apps/networkpolicies/allow-ingress-from-cloudflared.yaml
  - apps/networkpolicies/allow-egress-to-mariadb.yaml
  - apps/networkpolicies/allow-egress-to-opensearch.yaml
  - apps/networkpolicies/allow-egress-to-dragonfly.yaml
