apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/namespace.yaml
  - infrastructure/helm-repositories/opensearch.yaml
  - infrastructure/helm-repositories/stakater.yaml
  - infrastructure/reloader/namespace.yaml
  - infrastructure/reloader/release.yaml
  - infrastructure/mariadb/statefulset.yaml
  - infrastructure/mariadb/service.yaml
  - infrastructure/opensearch/release.yaml
  - infrastructure/cloudflared/deployment.yaml
  - apps/namespace.yaml
  - apps/magento/configmap.yaml
  - apps/magento/service.yaml
  - apps/magento/pvc.yaml
  - apps/magento/deployment.yaml
