---
apiVersion: v1
kind: ConfigMap
metadata:
  name: magento-config
  namespace: apps
data:
  MAGENTO_BASE_URL: https://shop.example.com/
  MAGENTO_DB_HOST: mariadb.infrastructure.svc.cluster.local
  MAGENTO_DB_PORT: "3306"
  MAGENTO_DB_NAME: magento
  MAGENTO_DB_USER: magento
  MAGENTO_OPENSEARCH_HOST: opensearch-cluster-master.infrastructure.svc.cluster.local
  MAGENTO_OPENSEARCH_PORT: "9200"
  MAGENTO_OPENSEARCH_INDEX_PREFIX: magento2
  MAGENTO_ADMIN_EMAIL: admin@example.com
  MAGENTO_ADMIN_FIRSTNAME: Admin
  MAGENTO_ADMIN_LASTNAME: User
  MAGENTO_LANGUAGE: en_US
  MAGENTO_TIMEZONE: UTC
  MAGENTO_CURRENCY: USD
  MAGENTO_BACKEND_FRONTNAME: admin
  MAGENTO_SEARCH_ENGINE: opensearch
